### ISSUE TITLE
load fails, junk in save file ?

### ISSUE THREAD

**Issue by simonmichael** [tlh/workgroups.el#1] opened 2011-02-18 16:19 UTC
Thanks, this looks really useful. I started by turning on workgroups mode, creating a workgroup, and saving. The saved workgroups file now contains:

```
(-*-workgroups-*- ((type . workgroup) (uid . 0) (name . "dashboard") (wconfig (type . wconfig) (left) (top) (width . 236) (height . 74) (sbars) (sbwid) (wtree ... ... ... ...))))
```

Loading gives an error, _Messages_ looks like:

```
...
Starting Emacs daemon.
Restarting server
When done with this frame, type C-x 5 0
(wrong-number-of-arguments nil 0)
wg-switch-to-window-buffer: Wrong type argument: stringp, nil
```

I'm using emacsclient -t with emacs --daemon, 23.0.50.1 on ubuntu lucid.

**Comment by tlh** [comment] 2011-02-18 17:01
This was a bug caused by not binding print-level to nil in `wg-write-sexp-to-file'.  I've pushed a fix.  Thanks!

**Closed as completed by tlh** 2011-02-18 17:01 UTC
